name: Create New Branch

on:
  schedule:
    # 매주 화요일 오전 9시
    #- cron: '0 9 * * 2'
    # 매주 목요일 오전 9시
    #- cron: '0 9 * * 4'
    - cron: '*/10 * * * *'

jobs:
  create-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: master  # master 브랜치를 체크아웃

      - name: Create new release branch
        run: |
          # Create a new branch name based on the current date and time
          BRANCH_NAME=/rls/new-branch-$(date +%Y%m%d%H%M%S)
          # Create the new branch from the default branch (main)
          git checkout -b $BRANCH_NAME
          # Push the new branch to the repository
          git push origin $BRANCH_NAME